### ISSUE TITLE
您好，使用ux-grid的默认方法进行表格排序时，获取不到排序后的数据

### ISSUE THREAD

**Issue by StarsLeopard** [u-fish-bubble/umy-ui#245]
您好，使用ux-grid的默认方法进行表格排序时，获取不到排序后的表格数据，看了umy-table的源码，发现ux-grid是基于elx-grid来撰写的，再往深层的源码就找不到了。请问作者有没有什么方法获取到经过排序后的表格数据么。或者请问下作者elx-grid组件是有开源仓库的么。谢谢

**Comment by crow04** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by StarsLeopard** [comment]
或者ux-grid能否向外暴露一下排序后的数据呢，希望作者空闲之后的时候能解答一下，十分感谢
