### ISSUE TITLE
您好，ux-grid使用 sortablejs 实现列的拖拽删除 当列较多时出现了以下错误 列较少并没有

### ISSUE THREAD

**Issue by wuboemo** [u-fish-bubble/umy-ui#258]
![微信图片_20240614161712](https://github.com/u-fish-bubble/umy-ui/assets/93749018/e5a001f9-871a-4eab-916f-7ec22cfeedf1)

**Comment by wuboemo** [comment]
目前我将x轴虚拟关闭之后好用了

**Comment by wuboemo** [comment]
目前我将x轴虚拟关闭之后好用了 但是数据量很大时 还是这个问题

**Comment by parlay96** [comment]
是的，这个需要自己去计算索引问题，因为这是虚拟表格，http://www.umyui.com/umycomponent/dragCol

**Comment by wuboemo** [comment]
我的意思是表格的数据多时进行拖拽会报上面的错误 而不是列过多时
